Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#Load the dataset
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
#print first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
#print the last 5 rows of the dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
41678,40781,-0.447381,1.134089,0.534095,-0.192366,1.344408,-0.370402,1.088646,-0.094025,-0.444502,...,-0.050234,-0.092340,-0.463501,-0.908485,0.202750,-0.506844,-0.058317,-0.085094,1.00,0.0
41679,40782,1.133168,0.406826,0.956032,2.315761,-0.242409,0.225013,-0.295703,0.130832,-0.768433,...,0.180411,0.487918,-0.121882,0.029950,0.465114,0.097369,0.010912,0.018509,10.65,0.0
41680,40783,-0.536190,1.355132,0.064049,0.884589,0.581654,-0.179437,0.466058,0.213312,-0.130088,...,-0.013520,0.198903,-0.112066,-0.505780,-0.266556,-0.349786,-0.367509,-0.399716,1.00,0.0
41681,40783,-0.498757,0.332449,1.917148,-2.340131,-1.098398,-0.863136,-0.055820,-0.084046,1.673677,...,0.371752,1.441352,-0.250882,0.483504,-0.140917,-0.613552,0.380606,0.226502,26.59,0.0
41682,40784,-0.621229,-0.733600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#data info
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41683 entries, 0 to 41682
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    41683 non-null  int64
 1   V1      41683 non-null  float64
 2   V2      41683 non-null  float64
 3   V3      41682 non-null  float64
 4   V4      41682 non-null  float64
 5   V5      41682 non-null  float64
 6   V6      41682 non-null  float64
 7   V7      41682 non-null  float64
 8   V8      41682 non-null  float64
 9   V9      41682 non-null  float64
 10  V10     41682 non-null  float64
 11  V11     41682 non-null  float64
 12  V12     41682 non-null  float64
 13  V13     41682 non-null  float64
 14  V14     41682 non-null  float64
 15  V15     41682 non-null  float64
 16  V16     41682 non-null  float64
 17  V17     41682 non-null  float64
 18  V18     41682 non-null  float64
 19  V19     41682 non-null  float64
 20  V20     41682 non-null  float64
 21  V21     41682 non-null  float64
 22  V22     41682 non-null  float64
 23  V23     41682 non-null  float64
 24  V24     41682 non-null  float64
 25  V25     41682 non-null  float64
 26  V26     41682 non-null  float64
 27  V27     41682 non-null  float64
 28  V28     41682 non-null  float64
 29  Amount  41682 non-null  float64
 30  Class   41682 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 9.9 MB

In [ ]:
#filling the missing values
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of legit and fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    41574
1.0      108
Name: count, dtype: int64

Since this dataset is highly unbalanced



0 --> normal transaction
1 --> fraud transaction

In [ ]:
#separating the data
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(41574, 31)
(108, 31)

In [ ]:
legit.Amount.describe()

count    41574.000000
mean        89.092554
std        237.129967
min          0.000000
25%          7.550000
50%         24.000000
75%         80.000000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     108.000000
mean       93.512593
std       250.863273
min         0.000000
25%         1.000000
50%         2.320000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#comapring the values
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,26220.447082,-0.203702,0.021029,0.74135,0.172070,-0.222039,0.105713,-0.093360,0.035106,0.201757,...,0.045420,-0.030057,-0.110755,-0.039591,0.007931,0.135806,0.022783,0.005968,0.004583,89.092554
1.0,21414.990741,-7.454643,5.595067,-10.62406,5.849772,-5.115950,-2.288288,-7.382457,3.691487,-2.904887,...,0.630658,0.602725,-0.336878,-0.313708,-0.237598,0.310378,0.183470,0.791559,0.112874,93.512593

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
#Concatenate the two DF's
new_data = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
37333,38912,-1.953491,-5.973115,-1.720123,0.879706,-2.681031,-0.260686,1.912005,-0.578127,-1.196026,...,0.645502,-1.479145,-1.492532,0.656207,-0.268747,0.881468,-0.398487,0.286274,1715.71,0.0
17009,28361,-1.590369,0.943229,2.112235,-0.384713,-0.536953,-0.397067,0.025082,0.479197,-0.332419,...,0.115638,0.093300,-0.210184,0.423399,0.054516,0.150061,-0.311007,-0.048652,27.20,0.0
24632,33309,-0.520444,1.256747,0.828181,-0.184439,0.369624,-0.515077,0.696417,-0.006809,-0.133171,...,-0.352388,-0.871494,-0.088326,-0.513536,0.004142,0.129675,0.354615,0.146746,7.99,0.0
37405,38944,0.703069,-1.794655,-0.842245,-1.996337,-1.051528,-1.077770,0.417841,-0.388540,-0.455142,...,-0.436754,-1.620690,-0.240820,-0.004163,0.249196,-0.327263,-0.076656,0.066761,390.00,0.0
27821,34715,-1.997486,-6.247751,-2.146480,0.828500,-2.484162,-0.205025,2.006526,-0.658223,-0.743316,...,1.187403,-0.648449,-1.788212,-0.005568,0.155405,-0.220592,-0.356211,0.307654,1800.00,0.0

In [ ]:
new_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0
40085,40086,1.083693,1.179501,-1.346150,1.998824,0.818034,-0.771419,0.230307,0.093683,-0.167594,...,-0.312000,-0.639700,-0.120249,-0.180218,0.609283,-0.339524,0.096701,0.114972,1.00,1.0
40525,40276,1.159373,2.844795,-4.050680,4.777701,2.948980,-2.010361,1.744086,-0.410287,-2.450198,...,-0.176541,-0.433470,-0.529323,-0.597020,1.335954,0.547092,0.009979,0.160769,1.00,1.0
41395,40662,-4.446847,-0.014793,-5.126307,6.945130,5.269255,-4.297177,-2.591242,0.342671,-3.880663,...,0.247913,-0.049586,-0.226017,-0.401236,0.856124,0.661272,0.492560,0.971834,1.00,1.0
41569,40742,-2.377533,0.520539,-8.094139,8.005351,2.640750,-3.381586,-1.934372,0.562322,-3.104027,...,0.148284,0.721100,2.661291,-0.508620,-0.401657,0.587611,0.500326,0.551760,1.00,1.0

In [ ]:
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,26206.666667,-0.209307,0.070358,0.640318,0.201241,-0.263346,0.205342,-0.104004,0.056259,0.210564,...,0.045026,0.015134,-0.120905,-0.073640,-0.017498,0.148981,0.028367,0.016331,0.007844,106.072358
1.0,21414.990741,-7.454643,5.595067,-10.624060,5.849772,-5.115950,-2.288288,-7.382457,3.691487,-2.904887,...,0.630658,0.602725,-0.336878,-0.313708,-0.237598,0.310378,0.183470,0.791559,0.112874,93.512593

In [ ]:
#splitting
X = new_data.drop(columns='Class', axis=1)
Y = new_data['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
37333  38912 -1.953491 -5.973115 -1.720123  0.879706 -2.681031 -0.260686
17009  28361 -1.590369  0.943229  2.112235 -0.384713 -0.536953 -0.397067
24632  33309 -0.520444  1.256747  0.828181 -0.184439  0.369624 -0.515077
37405  38944  0.703069 -1.794655 -0.842245 -1.996337 -1.051528 -1.077770
27821  34715 -1.997486 -6.247751 -2.146480  0.828500 -2.484162 -0.205025
...      ...       ...       ...       ...       ...       ...       ...
39183  39729 -0.964567 -1.643541 -0.187727  1.158253 -2.458336  0.852222
40085  40086  1.083693  1.179501 -1.346150  1.998824  0.818034 -0.771419
40525  40276  1.159373  2.844795 -4.050680  4.777701  2.948980 -2.010361
41395  40662 -4.446847 -0.014793 -5.126307  6.945130  5.269255 -4.297177
41569  40742 -2.377533  0.520539 -8.094139  8.005351  2.640750 -3.381586

             V7        V8        V9  ...       V20       V21       V22  \
37333  1.912005 -0.578127 -1.196026  ...  2.950839  0.645502 -1.479145
17009  0.025082  0.479197 -0.332419  ... -0.276152  0.115638  0.093300
24632  0.696417 -0.006809 -0.133171  ...  0.258514 -0.352388 -0.871494
37405  0.417841 -0.388540 -0.455142  ...  0.314709 -0.436754 -1.620690
27821  2.006526 -0.658223 -0.743316  ...  3.624423  1.187403 -0.648449
...         ...       ...       ...  ...       ...       ...       ...
39183  2.785163 -0.303609  0.940006  ...  1.784449  0.447180  0.536204
40085  0.230307  0.093683 -0.167594  ... -0.060159 -0.312000 -0.639700
40525  1.744086 -0.410287 -2.450198  ... -0.059264 -0.176541 -0.433470
41395 -2.591242  0.342671 -3.880663  ... -0.108006  0.247913 -0.049586
41569 -1.934372  0.562322 -3.104027  ... -0.634747  0.148284  0.721100

            V23       V24       V25       V26       V27       V28   Amount
37333 -1.492532  0.656207 -0.268747  0.881468 -0.398487  0.286274  1715.71
17009 -0.210184  0.423399  0.054516  0.150061 -0.311007 -0.048652    27.20
24632 -0.088326 -0.513536  0.004142  0.129675  0.354615  0.146746     7.99
37405 -0.240820 -0.004163  0.249196 -0.327263 -0.076656  0.066761   390.00
27821 -1.788212 -0.005568  0.155405 -0.220592 -0.356211  0.307654  1800.00
...         ...       ...       ...       ...       ...       ...      ...
39183  1.634061  0.203839  0.218749 -0.221886 -0.308555 -0.164500   776.83
40085 -0.120249 -0.180218  0.609283 -0.339524  0.096701  0.114972     1.00
40525 -0.529323 -0.597020  1.335954  0.547092  0.009979  0.160769     1.00
41395 -0.226017 -0.401236  0.856124  0.661272  0.492560  0.971834     1.00
41569  2.661291 -0.508620 -0.401657  0.587611  0.500326  0.551760     1.00

[600 rows x 30 columns]

In [ ]:
print(Y)

37333    0.0
17009    0.0
24632    0.0
37405    0.0
27821    0.0
        ...
39183    1.0
40085    1.0
40525    1.0
41395    1.0
41569    1.0
Name: Class, Length: 600, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(600, 30) (480, 30) (120, 30)

In [ ]:
#Model train
model = LogisticRegression()

In [ ]:
#training
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
#Accuracy
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9708333333333333

In [ ]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9666666666666667